<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $companies = [
            [
                'name' => 'Alexei Petrov',
                'email' => 'alexei@techsolutions.fi',
                'password' => Hash::make('password'),
                'role' => 'client',
                'business_name' => 'TechSolutions Finland',
                'industry' => 'Information Technology',
                'company_type' => 'Oy',
                'year_of_establishment' => 2021,
                'number_of_employees' => 8,
                'internet_address' => 'www.techsolutions.fi',
                'address' => 'Kalevankatu 15',
                'postal_district' => 'Helsinki',
                'zip_code' => '00100',
                'business_idea' => 'Providing cutting-edge software development services and digital transformation solutions for Finnish SMEs.',
                'products_services_general' => 'Custom software development, web applications, mobile apps, cloud solutions, IT consulting',
                'bio' => 'Passionate about technology and innovation. Building scalable solutions for growing businesses.',
                'specialization' => 'Software Development',
                'onboarding_completed_at' => now(),
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Sarah Johnson',
                'email' => 'sarah@greenfoods.fi',
                'password' => Hash::make('password'),
                'role' => 'client',
                'business_name' => 'GreenFoods Finland',
                'industry' => 'Food & Beverage',
                'company_type' => 'Oy',
                'year_of_establishment' => 2020,
                'number_of_employees' => 12,
                'internet_address' => 'www.greenfoods.fi',
                'address' => 'Mannerheimintie 45',
                'postal_district' => 'Helsinki',
                'zip_code' => '00260',
                'business_idea' => 'Organic and sustainable food products sourced from local Finnish farms.',
                'products_services_general' => 'Organic produce, plant-based foods, sustainable food packaging, catering services',
                'bio' => 'Committed to sustainable living and healthy food choices. Supporting local farmers and promoting eco-friendly practices.',
                'specialization' => 'Sustainable Food Production',
                'onboarding_completed_at' => now(),
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Mika Virtanen',
                'email' => 'mika@designstudio.fi',
                'password' => Hash::make('password'),
                'role' => 'client',
                'business_name' => 'Nordic Design Studio',
                'industry' => 'Creative & Design',
                'company_type' => 'Toiminimi',
                'year_of_establishment' => 2019,
                'number_of_employees' => 5,
                'internet_address' => 'www.nordicdesign.fi',
                'address' => 'Punavuorenkatu 3',
                'postal_district' => 'Helsinki',
                'zip_code' => '00120',
                'business_idea' => 'Minimalist Nordic design services for brands, products, and digital experiences.',
                'products_services_general' => 'Brand identity design, logo design, web design, product packaging, graphic design',
                'bio' => 'Inspired by Nordic aesthetics and minimalist philosophy. Creating timeless designs that tell stories.',
                'specialization' => 'Brand Design',
                'onboarding_completed_at' => now(),
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Elena Kovalenko',
                'email' => 'elena@wellnesscenter.fi',
                'password' => Hash::make('password'),
                'role' => 'client',
                'business_name' => 'Helsinki Wellness Center',
                'industry' => 'Health & Wellness',
                'company_type' => 'Oy',
                'year_of_establishment' => 2022,
                'number_of_employees' => 6,
                'internet_address' => 'www.helsinkiwellness.fi',
                'address' => 'Eteläranta 10',
                'postal_district' => 'Helsinki',
                'zip_code' => '00130',
                'business_idea' => 'Holistic wellness center offering yoga, meditation, massage therapy, and wellness coaching.',
                'products_services_general' => 'Yoga classes, meditation sessions, massage therapy, wellness workshops, corporate wellness programs',
                'bio' => 'Dedicated to helping people achieve balance and wellness in their daily lives.',
                'specialization' => 'Holistic Wellness',
                'onboarding_completed_at' => now(),
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Jussi Lehtonen',
                'email' => 'jussi@finnishcrafts.fi',
                'password' => Hash::make('password'),
                'role' => 'client',
                'business_name' => 'Finnish Crafts Co',
                'industry' => 'Retail & E-commerce',
                'company_type' => 'Oy',
                'year_of_establishment' => 2021,
                'number_of_employees' => 4,
                'internet_address' => 'www.finnishcrafts.fi',
                'address' => 'Kauppatori 1',
                'postal_district' => 'Helsinki',
                'zip_code' => '00170',
                'business_idea' => 'Handcrafted Finnish products and traditional crafts sold online and in local markets.',
                'products_services_general' => 'Handmade textiles, wooden products, traditional Finnish crafts, gift items, online retail',
                'bio' => 'Preserving Finnish craft traditions while creating modern products for contemporary homes.',
                'specialization' => 'Traditional Crafts',
                'onboarding_completed_at' => now(),
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Marina Andersson',
                'email' => 'marina@languagehub.fi',
                'password' => Hash::make('password'),
                'role' => 'client',
                'business_name' => 'Language Hub Finland',
                'industry' => 'Education',
                'company_type' => 'Oy',
                'year_of_establishment' => 2020,
                'number_of_employees' => 10,
                'internet_address' => 'www.languagehub.fi',
                'address' => 'Yliopistonkatu 5',
                'postal_district' => 'Helsinki',
                'zip_code' => '00100',
                'business_idea' => 'Language learning services specializing in Finnish, Swedish, and English for professionals and immigrants.',
                'products_services_general' => 'Finnish language courses, business Finnish, Swedish lessons, English training, online courses, corporate training',
                'bio' => 'Passionate about language learning and helping people integrate into Finnish society through language.',
                'specialization' => 'Language Education',
                'onboarding_completed_at' => now(),
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Tommi Hakkarainen',
                'email' => 'tommi@cleanenergy.fi',
                'password' => Hash::make('password'),
                'role' => 'client',
                'business_name' => 'CleanEnergy Solutions',
                'industry' => 'Energy & Environment',
                'company_type' => 'Oy',
                'year_of_establishment' => 2021,
                'number_of_employees' => 15,
                'internet_address' => 'www.cleanenergy.fi',
                'address' => 'Tekniikantie 21',
                'postal_district' => 'Espoo',
                'zip_code' => '02150',
                'business_idea' => 'Renewable energy solutions including solar panel installation, energy consulting, and sustainable energy systems.',
                'products_services_general' => 'Solar panel installation, energy audits, sustainable energy consulting, battery storage systems, EV charging solutions',
                'bio' => 'Committed to Finland\'s carbon-neutral future through innovative clean energy solutions.',
                'specialization' => 'Renewable Energy',
                'onboarding_completed_at' => now(),
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Liisa Korhonen',
                'email' => 'liisa@eventplanning.fi',
                'password' => Hash::make('password'),
                'role' => 'client',
                'business_name' => 'Event Planning Helsinki',
                'industry' => 'Events & Hospitality',
                'company_type' => 'Toiminimi',
                'year_of_establishment' => 2019,
                'number_of_employees' => 7,
                'internet_address' => 'www.eventplanninghelsinki.fi',
                'address' => 'Esplanadi 22',
                'postal_district' => 'Helsinki',
                'zip_code' => '00130',
                'business_idea' => 'Full-service event planning and management for corporate events, weddings, and private celebrations.',
                'products_services_general' => 'Corporate event planning, wedding coordination, venue selection, catering coordination, event design',
                'bio' => 'Creating unforgettable experiences and memorable events for clients across Finland.',
                'specialization' => 'Event Management',
                'onboarding_completed_at' => now(),
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Anton Berglund',
                'email' => 'anton@fitnessapp.fi',
                'password' => Hash::make('password'),
                'role' => 'client',
                'business_name' => 'FitnessApp Finland',
                'industry' => 'Technology & Health',
                'company_type' => 'Oy',
                'year_of_establishment' => 2022,
                'number_of_employees' => 9,
                'internet_address' => 'www.fitnessapp.fi',
                'address' => 'Töölönkatu 2',
                'postal_district' => 'Helsinki',
                'zip_code' => '00260',
                'business_idea' => 'Mobile fitness app combining AI-powered personal training with Finnish wellness culture.',
                'products_services_general' => 'Fitness mobile app, personal training plans, nutrition tracking, workout videos, community features',
                'bio' => 'Tech entrepreneur focused on making fitness accessible and personalized through AI and mobile technology.',
                'specialization' => 'Fitness Technology',
                'onboarding_completed_at' => now(),
                'email_verified_at' => now(),
            ],
            [
                'name' => 'Katri Nieminen',
                'email' => 'katri@consultinggroup.fi',
                'password' => Hash::make('password'),
                'role' => 'client',
                'business_name' => 'Nieminen Consulting Group',
                'industry' => 'Business Consulting',
                'company_type' => 'Oy',
                'year_of_establishment' => 2020,
                'number_of_employees' => 11,
                'internet_address' => 'www.nieminenconsulting.fi',
                'address' => 'Aleksanterinkatu 9',
                'postal_district' => 'Helsinki',
                'zip_code' => '00100',
                'business_idea' => 'Strategic business consulting services for startups and growing companies in Finland.',
                'products_services_general' => 'Business strategy consulting, market research, financial planning, growth strategies, startup advisory',
                'bio' => 'Helping Finnish businesses grow and succeed through strategic planning and expert consulting.',
                'specialization' => 'Business Strategy',
                'onboarding_completed_at' => now(),
                'email_verified_at' => now(),
            ],
        ];

        foreach ($companies as $company) {
            User::updateOrCreate(
                ['email' => $company['email']],
                $company
            );
        }
    }
}
